// Generated by scripts/sync-roms.mjs. Do not edit.
export default {
  "build-minesweeper": {
    "name": "minesweeper",
    "description": "FAMI-C build/minesweeper.nes",
    "url": "/roms/minesweeper.nes"
  },
  "build-tetris": {
    "name": "tetris",
    "description": "FAMI-C build/tetris.nes",
    "url": "/roms/tetris.nes"
  }
};
