import { copyFile, mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const projectRoot = path.resolve(webRoot, "..", "..");
const sourceDir = path.join(projectRoot, "build");
const targetDir = path.join(webRoot, "public", "roms");
const generatedFile = path.join(webRoot, "src", "generatedRoms.js");

await mkdir(targetDir, { recursive: true });

const files = (await readdir(sourceDir, { withFileTypes: true }))
  .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".nes"))
  .map((entry) => entry.name)
  .sort((a, b) => a.localeCompare(b));

const roms = {};
for (const file of files) {
  await copyFile(path.join(sourceDir, file), path.join(targetDir, file));
  const slug = `build-${path.basename(file, path.extname(file)).replace(/[^a-z0-9_-]/gi, "-").toLowerCase()}`;
  roms[slug] = {
    name: path.basename(file, path.extname(file)),
    description: `FAMI-C build/${file}`,
    url: `/roms/${encodeURIComponent(file)}`,
  };
}

await writeFile(
  generatedFile,
  `// Generated by scripts/sync-roms.mjs. Do not edit.\nexport default ${JSON.stringify(roms, null, 2)};\n`,
);

console.log(`Synced ${files.length} ROM(s) from ${sourceDir}`);
