#!/usr/bin/env python3
"""Build the Tetris ROM and exercise it in Mesen's headless test runner."""

from __future__ import annotations

import argparse
from pathlib import Path
import subprocess
import sys
import tempfile

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from famic import Assembler, build_rom, compile_c_to_asm  # noqa: E402


def find_mesen(explicit: Path | None) -> Path:
    candidates = []
    if explicit is not None:
        candidates.append(explicit)
    candidates.append(Path.home() / "Downloads" / "Mesen_2.2.1_Windows" / "Mesen.exe")
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    raise FileNotFoundError("Mesen.exe not found; pass --mesen PATH")


def lua_script(symbols: dict[str, int]) -> str:
    required = {
        "board": "_board",
        "game_state": "_game_state",
        "piece_x": "_piece_x",
        "piece_y": "_piece_y",
        "piece_t": "_piece_t",
        "piece_r": "_piece_r",
        "old_piece_x": "_old_piece_x",
        "old_piece_y": "_old_piece_y",
        "old_piece_r": "_old_piece_r",
        "piece_dirty": "_piece_dirty",
        "lock_pending": "_lock_pending",
        "drop_tick": "_drop_tick",
        "lock_tick": "_lock_tick",
        "erase_count": "_erase_count",
        "draw_count": "_draw_count",
        "pad": "_pad",
        "prev_pad": "_prev_pad",
        "next_piece": "_next_piece",
        "score_digits": "_score_digits",
        "line_digits": "_line_digits",
        "level": "_level",
        "bag": "_bag",
        "bag_pos": "_bag_pos",
        "rng_state": "_rng_state",
        "rng_state_hi": "_rng_state_hi",
        "masks": "_MASKS",
        "shapes": "_SHAPES",
        "preview_shift": "_PREVIEW_SHIFT",
        "game_attributes": "_GAME_ATTRIBUTES",
        "start_level": "_start_level",
        "hi_score": "_hi_score",
        "music_enabled": "__music_enabled",
        "music_step": "__music_step",
        "music_phase_lo": "__music_phase_lo",
        "music_phase_hi": "__music_phase_hi",
        "music_phase_inc_lo": "__music_phase_inc_lo",
        "music_phase_inc_hi": "__music_phase_inc_hi",
        "music_order_lo": "__music_order_lo",
        "music_order_page": "__music_order_page",
        "music_pattern_step": "__music_pattern_step",
    }
    address = {name: symbols[label] for name, label in required.items()}
    return f"""-- Generated by tools/run_mesen_smoke.py
local frame = 0
local failures = {{}}
local firstX = -1
local firstRotation = -1
local firstMusicStep = -1
local droppedPiece = -1
local needsSecondRotation = false
local ppuTimingArmed = false
local invalidPpuWrite = nil
local lastTitleRng = nil
local titleRngTransitions = 0
local lastBagSignature = nil
local checkedBagCount = 0
local musicAuditActive = false
local musicAuditSteps = 0
local mem = emu.memType.nesDebug
local ppuMem = emu.memType.nesPpuDebug

local BOARD_W = 10
local BOARD_H = 20
local BOARD_X = 10
local BOARD_Y = 4
local NEXT_X = 23
local NEXT_Y = 7

local function read(address)
    return emu.read(address, mem)
end

local function write(address, value)
    emu.write(address, value, mem)
end

local function readPpu(x, y)
    return emu.read(0x2000 + (y * 32) + x, ppuMem)
end

local function writePpu(x, y, value)
    emu.write(0x2000 + (y * 32) + x, value, ppuMem)
end

local function expect(condition, message)
    if not condition then
        table.insert(failures, message)
    end
end

local function readRng()
    return read({address['rng_state']}) | (read({address['rng_state_hi']}) << 8)
end

local function nextLfsr(state)
    local result = state >> 1
    if (state & 1) ~= 0 then
        result = result ~ 0xB400
    end
    return result & 0xFFFF
end

local function monitorTitleRng()
    local current = readRng()
    if lastTitleRng ~= nil then
        local expected = nextLfsr(lastTitleRng)
        expect(
            current == expected,
            string.format(
                "title RNG did not advance exactly once: previous=$%04X expected=$%04X actual=$%04X",
                lastTitleRng, expected, current
            )
        )
        titleRngTransitions = titleRngTransitions + 1
    end
    lastTitleRng = current
end

local function expectBagPermutation(tag)
    local seen = {{}}
    local values = {{}}

    for index = 0, 6 do
        local piece = read({address['bag']} + index)
        values[index + 1] = piece
        expect(
            piece < 7,
            string.format("%s bag[%d] was outside 0..6: %d", tag, index, piece)
        )
        if piece < 7 then
            expect(
                seen[piece] == nil,
                string.format("%s bag repeated piece %d", tag, piece)
            )
            seen[piece] = true
        end
    end

    for piece = 0, 6 do
        expect(seen[piece] == true, string.format("%s bag omitted piece %d", tag, piece))
    end
    checkedBagCount = checkedBagCount + 1
    return table.concat(values, ",")
end

local function monitorBag()
    local state = read({address['game_state']})
    if state ~= 1 and state ~= 2 then
        return
    end

    local position = read({address['bag_pos']})
    expect(position <= 7, string.format("bag_pos was outside 0..7: %d", position))

    local values = {{}}
    for index = 0, 6 do
        values[index + 1] = read({address['bag']} + index)
    end
    local signature = table.concat(values, ",")
    if signature ~= lastBagSignature then
        lastBagSignature = expectBagPermutation(
            string.format("observed bag %d", checkedBagCount + 1)
        )
    end
end

local function expectGameAttributes(tag)
    for offset = 0, 63 do
        local expected = read({address['game_attributes']} + offset)
        local actual = emu.read(0x23C0 + offset, ppuMem)
        expect(
            actual == expected,
            string.format(
                "%s attribute mismatch at $%04X: expected=$%02X actual=$%02X",
                tag, 0x23C0 + offset, expected, actual
            )
        )
    end
end

local function shapeCell(piece, rotation, x, y)
    local offset = (((piece * 4) + rotation) * 4) + y
    local row = read({address['shapes']} + offset)
    local mask = read({address['masks']} + x)
    return (row & mask) ~= 0
end

local function shapeMinX(piece, rotation)
    local minX = 4
    for y = 0, 3 do
        for x = 0, 3 do
            if shapeCell(piece, rotation, x, y) and x < minX then
                minX = x
            end
        end
    end
    return minX
end

local function expectNextLabel()
    local expected = {{ 39, 30, 49, 45 }}
    for x = 0, 3 do
        expect(
            readPpu(NEXT_X + x, 5) == expected[x + 1],
            string.format("NEXT label mismatch at x=%d", x)
        )
    end
end

local function expectNextPreview(tag)
    local nextPiece = read({address['next_piece']})
    local nonzero = 0
    local expected = {{}}

    expect(nextPiece < 7, tag .. " next_piece was outside 0..6")
    if nextPiece >= 7 then
        return
    end

    for index = 1, 16 do
        expected[index] = 0
    end

    -- Spawn shapes already sit against the left of their 4x4 grid, so the
    -- preview only nudges the three-wide pieces down a row to line them up
    -- with the I and O previews.
    local previewShift = read({address['preview_shift']} + nextPiece)
    for y = 0, 3 do
        for x = 0, 3 do
            if shapeCell(nextPiece, 0, x, y) then
                local previewY = y + previewShift
                expect(previewY < 4, tag .. " preview row overflowed the box")
                expected[(previewY * 4) + x + 1] = nextPiece + 1
            end
        end
    end

    for y = 0, 3 do
        for x = 0, 3 do
            local expectedTile = expected[(y * 4) + x + 1]
            local actualTile = readPpu(NEXT_X + x, NEXT_Y + y)
            if actualTile ~= 0 then
                nonzero = nonzero + 1
            end
            expect(
                actualTile == expectedTile,
                string.format(
                    "%s NEXT mismatch at (%d,%d): piece=%d expected=%d actual=%d",
                    tag, x, y, nextPiece, expectedTile, actualTile
                )
            )
        end
    end
    expect(nonzero == 4, string.format("%s NEXT contained %d occupied tiles", tag, nonzero))
end

-- The TOP panel mirrors the leading best-player score while a game runs.
local function expectTopPanel()
    local label = {{ 45, 40, 41 }}
    for x = 0, 2 do
        expect(
            readPpu(23 + x, 14) == label[x + 1],
            string.format("TOP label mismatch at x=%d", x)
        )
    end
    for index = 0, 5 do
        local digit = read({address['hi_score']} + (5 - index))
        expect(
            readPpu(22 + index, 16) == 16 + digit,
            string.format("TOP score mismatch at digit %d", index)
        )
    end
end

-- One eight-tile status row in the right-hand column.
local function expectStatusLine(y, tiles, tag)
    for x = 0, 7 do
        expect(
            readPpu(22 + x, y) == tiles[x + 1],
            string.format(
                "%s status mismatch at (%d,%d): expected=%d actual=%d",
                tag, 22 + x, y, tiles[x + 1], readPpu(22 + x, y)
            )
        )
    end
end

local function countBoardCells()
    local count = 0
    for offset = 0, (BOARD_W * BOARD_H) - 1 do
        if read({address['board']} + offset) ~= 0 then
            count = count + 1
        end
    end
    return count
end

local function expectActivePieceAtLeftEdge()
    local piece = read({address['piece_t']})
    local rotation = read({address['piece_r']})
    local pieceX = read({address['piece_x']})
    local pieceY = read({address['piece_y']})
    local minX = shapeMinX(piece, rotation)
    local expectedOrigin = (256 - minX) % 256
    local edgeCells = 0

    expect(minX < 4, "active tetromino had no occupied cells")
    expect(
        pieceX == expectedOrigin,
        string.format("left DAS stopped at piece_x=%d; expected %d", pieceX, expectedOrigin)
    )
    expect(
        ((pieceX + minX) % 256) == 0,
        string.format("leftmost occupied board column was %d, not 0", (pieceX + minX) % 256)
    )

    for y = 0, 3 do
        for x = 0, 3 do
            if shapeCell(piece, rotation, x, y) and ((pieceX + x) % 256) == 0 then
                edgeCells = edgeCells + 1
                expect(
                    readPpu(BOARD_X, BOARD_Y + pieceY + y) == piece + 1,
                    string.format("active piece was missing from PPU board column 0 at local y=%d", y)
                )
            end
        end
    end
    expect(edgeCells > 0, "active tetromino had no cell in board column 0")
    droppedPiece = piece
end

local function expectLockedPieceAtLeftEdge()
    local expectedTile = droppedPiece + 1
    local edgeCells = 0

    for y = 0, BOARD_H - 1 do
        local tile = read({address['board']} + (y * BOARD_W))
        if tile == expectedTile then
            edgeCells = edgeCells + 1
            expect(
                readPpu(BOARD_X, BOARD_Y + y) == expectedTile,
                string.format("locked piece RAM/PPU mismatch in board column 0 at y=%d", y)
            )
        end
    end
    expect(edgeCells > 0, "hard-dropped tetromino did not occupy board column 0")
end

local function fixtureTile(x, y)
    if y == BOARD_H - 1 then
        if x <= 3 or x >= 8 then
            return ((x + 4) % 7) + 1
        end
        return 0
    end

    if x == 0 then
        return (y % 7) + 1
    elseif x == BOARD_W - 1 then
        return ((y + 3) % 7) + 1
    end
    return 0
end

local function expectedClearedTile(x, y)
    if y == 0 then
        return 0
    end
    return fixtureTile(x, y - 1)
end

local function prepareLineClear()
    expect(read({address['game_state']}) == 1, "line-clear fixture did not start in gameplay")

    for y = 0, BOARD_H - 1 do
        for x = 0, BOARD_W - 1 do
            local tile = fixtureTile(x, y)
            write({address['board']} + (y * BOARD_W) + x, tile)
            writePpu(BOARD_X + x, BOARD_Y + y, tile)
        end
    end

    for index = 0, 5 do
        write({address['score_digits']} + index, 0)
    end
    for index = 0, 2 do
        write({address['line_digits']} + index, 0)
    end
    write({address['level']}, 0)
    for x = 1, 6 do
        writePpu(x, 7, 16)
    end
    for x = 3, 5 do
        writePpu(x, 13, 16)
    end
    writePpu(3, 19, 16)
    writePpu(4, 19, 16)

    -- A horizontal I at x=4 falls through the sparse sentinels and fills
    -- exactly the four-cell gap in the bottom row.
    write({address['piece_t']}, 0)
    write({address['piece_r']}, 0)
    write({address['piece_x']}, 4)
    write({address['piece_y']}, 0)
    write({address['old_piece_x']}, 4)
    write({address['old_piece_y']}, 0)
    write({address['old_piece_r']}, 0)
    write({address['piece_dirty']}, 0)
    write({address['lock_pending']}, 0)
    write({address['drop_tick']}, 0)
    write({address['lock_tick']}, 0)
    write({address['erase_count']}, 0)
    write({address['draw_count']}, 0)
    write({address['pad']}, 0)
    write({address['prev_pad']}, 0)

    for x = 4, 7 do
        writePpu(BOARD_X + x, BOARD_Y + 1, 1)
    end
end

local function expectLineClearBoard()
    local overlay = {{}}
    local piece = read({address['piece_t']})
    local rotation = read({address['piece_r']})
    local pieceX = read({address['piece_x']})
    local pieceY = read({address['piece_y']})

    for y = 0, 3 do
        for x = 0, 3 do
            if shapeCell(piece, rotation, x, y) then
                local boardX = (pieceX + x) % 256
                local boardY = pieceY + y
                if boardX < BOARD_W and boardY < BOARD_H then
                    overlay[(boardY * BOARD_W) + boardX] = piece + 1
                end
            end
        end
    end

    for y = 0, BOARD_H - 1 do
        for x = 0, BOARD_W - 1 do
            local offset = (y * BOARD_W) + x
            local expectedRam = expectedClearedTile(x, y)
            local actualRam = read({address['board']} + offset)
            local expectedPpu = overlay[offset]
            if expectedPpu == nil then
                expectedPpu = expectedRam
            end
            local actualPpu = readPpu(BOARD_X + x, BOARD_Y + y)

            expect(
                actualRam == expectedRam,
                string.format(
                    "line-clear board RAM mismatch at (%d,%d): expected=%d actual=%d",
                    x, y, expectedRam, actualRam
                )
            )
            expect(
                actualPpu == expectedPpu,
                string.format(
                    "line-clear board PPU mismatch at (%d,%d): expected=%d actual=%d",
                    x, y, expectedPpu, actualPpu
                )
            )
        end
    end
end

local function expectBoardFrame()
    expect(readPpu(9, 3) == 54, "top-left frame corner was corrupted")
    expect(readPpu(20, 3) == 56, "top-right frame corner was corrupted")
    expect(readPpu(9, 24) == 59, "bottom-left frame corner was corrupted")
    expect(readPpu(20, 24) == 61, "bottom-right frame corner was corrupted")

    for x = 10, 19 do
        expect(readPpu(x, 3) == 55, string.format("top frame rail corrupted at x=%d", x))
        expect(readPpu(x, 24) == 60, string.format("bottom frame rail corrupted at x=%d", x))
    end
    for y = 4, 23 do
        expect(readPpu(9, y) == 57, string.format("left frame rail corrupted at y=%d", y))
        expect(readPpu(20, y) == 58, string.format("right frame rail corrupted at y=%d", y))
    end
end

local function expectLineClearScore()
    local expectedScoreRam = {{ 0, 4, 0, 0, 0, 0 }}
    local expectedScorePpu = {{ 16, 16, 16, 16, 20, 16 }}

    for index = 0, 5 do
        expect(
            read({address['score_digits']} + index) == expectedScoreRam[index + 1],
            string.format("score RAM mismatch at digit %d", index)
        )
        expect(
            readPpu(1 + index, 7) == expectedScorePpu[index + 1],
            string.format("score PPU mismatch at x=%d", 1 + index)
        )
    end

    expect(read({address['line_digits']}) == 1, "line counter ones digit was not 1")
    expect(read({address['line_digits']} + 1) == 0, "line counter tens digit was not 0")
    expect(read({address['line_digits']} + 2) == 0, "line counter hundreds digit was not 0")
    expect(readPpu(3, 13) == 16, "line counter hundreds tile was corrupted")
    expect(readPpu(4, 13) == 16, "line counter tens tile was corrupted")
    expect(readPpu(5, 13) == 17, "line counter ones tile did not show 1")
    expect(read({address['level']}) == 0, "single line unexpectedly changed the level")
    expect(readPpu(3, 19) == 16 and readPpu(4, 19) == 16, "level display was corrupted")
end

local function expectLineClearResult()
    expect(read({address['game_state']}) == 1, "line clear unexpectedly left gameplay")
    expect(read({address['lock_pending']}) == 0, "line clear was still pending")
    expect(invalidPpuWrite == nil, invalidPpuWrite or "")
    expectLineClearBoard()
    expectBoardFrame()
    expectGameAttributes("after line clear")
    expectLineClearScore()
    expectNextLabel()
    expectNextPreview("after line clear")
end

-- Armed for the whole gameplay phase: the status column, the line-clear flash
-- and the board refresh all have to finish inside vblank.
local function onPpuRegisterWrite(address, value)
    if not ppuTimingArmed or invalidPpuWrite ~= nil then
        return
    end

    local state = emu.getState()
    local scanline = state["ppu.scanline"]
    local cycle = state["ppu.cycle"]
    local rendering = state["ppu.mask.backgroundEnabled"] or state["ppu.mask.spritesEnabled"]
    if rendering and scanline < 240 then
        invalidPpuWrite = string.format(
            "PPU register $%04X written during rendering at scanline=%d cycle=%d",
            address, scanline, cycle
        )
    end
end

local function finish()
    expect(titleRngTransitions >= 17, "too few title-frame RNG transitions were checked")
    expect(checkedBagCount >= 1, "no randomized 7-bag was observed")
    expect(invalidPpuWrite == nil, invalidPpuWrite or "")
    if #failures > 0 then
        for _, message in ipairs(failures) do
            emu.log("FAIL: " .. message)
            print("FAIL: " .. message)
        end
        emu.stop(1)
    else
        emu.log("PASS: title RNG, 7-bag, attributes, full-song music loop, movement, left edge, NEXT, hard drop, pause and line clear")
        print("PASS: title RNG, 7-bag, attributes, full-song music loop, movement, left edge, NEXT, hard drop, pause and line clear")
        emu.stop(0)
    end
end

local function startMusicAudit()
    -- Pausing keeps the main loop to exactly one wait_vblank/NMI between
    -- controller polls while leaving the NMI-owned music driver running.
    write({address['game_state']}, 2)
    write({address['music_step']}, 0)
    write({address['music_order_lo']}, 0)
    write({address['music_order_page']}, 0)
    write({address['music_pattern_step']}, 0)
    write({address['music_phase_inc_lo']}, 0x30)
    write({address['music_phase_inc_hi']}, 0x27)
    write({address['music_phase_lo']}, 0xFF)
    write({address['music_phase_hi']}, 0xFF)
    musicAuditSteps = 0
    musicAuditActive = true
end

local function auditMusicStep()
    musicAuditSteps = musicAuditSteps + 1

    local position = musicAuditSteps % 2448
    local expectedOrder = math.floor(position / 8)
    local expectedPattern = position % 8
    local expectedOrderLo = expectedOrder % 256
    local expectedOrderPage = math.floor(expectedOrder / 256)
    local actualOrderLo = read({address['music_order_lo']})
    local actualOrderPage = read({address['music_order_page']})
    local actualPattern = read({address['music_pattern_step']})
    local actualStep = read({address['music_step']})

    expect(
        actualOrderLo == expectedOrderLo and actualOrderPage == expectedOrderPage,
        string.format(
            "music order mismatch after forced step %d: expected=%d ($%02X:$%02X) actual=$%02X:$%02X",
            musicAuditSteps, expectedOrder, expectedOrderPage, expectedOrderLo,
            actualOrderPage, actualOrderLo
        )
    )
    expect(
        actualPattern == expectedPattern,
        string.format(
            "music pattern step mismatch after forced step %d: expected=%d actual=%d",
            musicAuditSteps, expectedPattern, actualPattern
        )
    )
    expect(
        actualStep == (musicAuditSteps % 256),
        string.format(
            "music step counter mismatch after forced step %d: expected=%d actual=%d",
            musicAuditSteps, musicAuditSteps % 256, actualStep
        )
    )

    if musicAuditSteps == 1937 then
        expect(
            read({address['music_phase_inc_lo']}) == 0x7C and
                read({address['music_phase_inc_hi']}) == 0x25,
            "music did not switch to the $257C increment after order 242 step 0"
        )
    elseif musicAuditSteps == 1945 then
        expect(
            read({address['music_phase_inc_lo']}) == 0x30 and
                read({address['music_phase_inc_hi']}) == 0x27,
            "music did not restore the $2730 increment after order 243 step 0"
        )
    end

    if musicAuditSteps == 2448 then
        expect(actualOrderLo == 0, "full-song loop did not return order low byte to 0")
        expect(actualOrderPage == 0, "full-song loop did not return order page to 0")
        expect(actualPattern == 0, "full-song loop did not return pattern step to 0")
        musicAuditActive = false
        finish()
        return
    end

    -- $FFFF guarantees a carry on the next NMI for either legal increment.
    write({address['music_phase_lo']}, 0xFF)
    write({address['music_phase_hi']}, 0xFF)
end

local function onInputPolled()
    frame = frame + 1
    local input = {{
        a = false, b = false, select = false, start = false,
        up = false, down = false, left = false, right = false
    }}

    -- The title screen draws its logo, level picker and best-player table
    -- before main() starts polling, so every phase below leaves generous
    -- slack for the multi-vblank drawing helpers.
    if frame >= 55 and frame <= 61 then
        input.start = true
    elseif frame >= 130 and frame <= 146 then
        input.right = true
    elseif frame >= 160 and frame <= 166 then
        input.a = true
    elseif needsSecondRotation and frame >= 185 and frame <= 191 then
        input.a = true
    elseif frame >= 205 and frame <= 265 then
        input.left = true
    elseif frame >= 280 and frame <= 286 then
        input.up = true
    elseif frame >= 345 and frame <= 351 then
        input.start = true
    elseif frame >= 385 and frame <= 391 then
        input.start = true
    elseif frame >= 445 and frame <= 451 then
        input.up = true
    end
    emu.setInput(input, 0)

    if musicAuditActive then
        auditMusicStep()
        return
    end

    if frame >= 25 and frame <= 50 and read({address['game_state']}) == 0 then
        monitorTitleRng()
    end
    monitorBag()

    if frame == 50 then
        expect(read({address['game_state']}) == 0, "title state was not reached")
        expect(read({address['music_enabled']}) == 1, "music driver was not enabled")
        expect(read({address['start_level']}) == 0, "level picker did not default to 0")
        firstMusicStep = read({address['music_step']})
    elseif frame == 120 then
        expect(read({address['game_state']}) == 1, "START did not enter gameplay")
        expect(read({address['level']}) == 0, "gameplay did not start at the picked level")
        firstX = read({address['piece_x']})
        firstRotation = read({address['piece_r']})
        expectGameAttributes("initial game")
        expectBoardFrame()
        expectNextLabel()
        expectNextPreview("initial")
        expectTopPanel()
        ppuTimingArmed = true
    elseif frame == 155 then
        expect(read({address['piece_x']}) > firstX, "right movement/DAS did not move the piece")
    elseif frame == 180 then
        expect(read({address['piece_r']}) ~= firstRotation, "A did not rotate the piece")
        needsSecondRotation = shapeMinX(
            read({address['piece_t']}), read({address['piece_r']})
        ) == 0
    elseif frame == 200 then
        expect(
            shapeMinX(read({address['piece_t']}), read({address['piece_r']})) > 0,
            "could not select a rotation with left padding for the edge test"
        )
    elseif frame == 275 then
        expectActivePieceAtLeftEdge()
    elseif frame == 335 then
        expect(countBoardCells() >= 4, "hard drop did not lock a tetromino")
        expectLockedPieceAtLeftEdge()
        expectNextLabel()
        expectNextPreview("updated")
        expect(read({address['game_state']}) == 1, "game unexpectedly left gameplay")
    elseif frame == 375 then
        expect(read({address['game_state']}) == 2, "START did not pause")
        expectStatusLine(21, {{ 0, 41, 26, 46, 44, 30, 29, 0 }}, "paused")
    elseif frame == 425 then
        expect(read({address['game_state']}) == 1, "START did not resume")
        expect(read({address['music_step']}) ~= firstMusicStep, "BGM sequencer did not advance")
        expectStatusLine(20, {{ 26, 52, 27, 0, 43, 40, 45, 0 }}, "resumed")
    elseif frame == 435 then
        prepareLineClear()
    elseif frame == 530 then
        expectLineClearResult()
        startMusicAudit()
    end
end

emu.addEventCallback(onInputPolled, emu.eventType.inputPolled)
emu.addMemoryCallback(
    onPpuRegisterWrite,
    emu.callbackType.write,
    0x2005,
    0x2007,
    emu.cpuType.nes,
    emu.memType.nesMemory
)
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mesen", type=Path, help="path to Mesen.exe")
    parser.add_argument("--timeout", type=int, default=15)
    args = parser.parse_args()

    mesen = find_mesen(args.mesen)
    source_path = PROJECT_ROOT / "examples" / "tetris.c"
    source = source_path.read_text(encoding="utf-8")
    assembly = compile_c_to_asm(source)
    assembler = Assembler()
    assembler.assemble(assembly)

    with tempfile.TemporaryDirectory(prefix="famic-mesen-") as temp:
        temp_path = Path(temp)
        rom_path = temp_path / "tetris.nes"
        lua_path = temp_path / "smoke.lua"
        build_rom(source_path, rom_path, None)
        lua_path.write_text(lua_script(assembler.symbols), encoding="utf-8")
        command = [
            str(mesen),
            "--testRunner",
            f"--timeout={args.timeout}",
            "--enableStdout",
            str(lua_path),
            str(rom_path),
        ]
        result = subprocess.run(command, cwd=PROJECT_ROOT, text=True, capture_output=True)

    if result.stdout.strip():
        print(result.stdout.strip())
    if result.stderr.strip():
        print(result.stderr.strip(), file=sys.stderr)
    if result.returncode != 0:
        print(f"Mesen smoke test failed with exit code {result.returncode}", file=sys.stderr)
        return result.returncode or 1
    print("Mesen smoke test passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
